### ISSUE TITLE
after installing this plugin, the app exits automatically (force close)

### ISSUE THREAD

**Issue by atmanegara** [HaylLtd/cordova-plugin-background-geolocation#83] opened 2022-06-04 20:40 UTC
**Describe the bug**
like the title

**To Reproduce**
1. install plugin 
2. copy paste example from https://haylltd.github.io/cordova-background-geolocation-plugin/example , not modify source
3. cordova run android

**Screenshots**
<img width="225" alt="image" src="https://user-images.githubusercontent.com/9096711/172024768-39c73f12-282d-40c8-b0ca-254d2d60cd5c.png">

**Smartphone (please complete the following information):**
 - Device: readmi
 - OS: android 11
 - cordova CLI : 11
 - cordova-android : 10.0.1

**Comment by HarelM** [comment] 2022-06-05 04:20
I'm not aware of crashes caused by this plugin, you'll need to debug using android studio to see where it crashes...

**Comment by ivinantony** [comment] 2022-06-06 02:11
This was happened in android for me too. You need to ask activity recognition permission before the location permission. Otherwise the app was getting crashed

**Comment by atmanegara** [comment] 2022-06-06 03:40
> This was happened in android for me too. You need to ask activity recognition permission before the location permission. Otherwise the app was getting crashed

how to add it?
- androidManifest.xml
<img width="546" alt="image" src="https://user-images.githubusercontent.com/9096711/172090707-3633fb26-093e-4849-b4d4-b692a7c33775.png">
- config.xml
<img width="538" alt="image" src="https://user-images.githubusercontent.com/9096711/172090776-955fd8e7-160c-499c-b449-ada4dd657e73.png">

**Comment by atmanegara** [comment] 2022-06-06 03:41
> I'm not aware of crashes caused by this plugin, you'll need to debug using android studio to see where it crashes...

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/9096711/172090823-8ff408ea-fa49-4449-96b2-ff2beebb7778.png">

**Comment by ivinantony** [comment] 2022-06-06 03:51
Use the android permission plugin and request for the permission before asking the location permission

**Comment by ivinantony** [comment] 2022-06-06 03:52
this.androidPermissions.requestPermission('android.permission.ACTIVITY_RECOGNITION') .then(result => { if (!result.hasPermission){ this.permissionActivity = false; }else{ this.permissionActivity = true; } }) .catch(err=>{ this.permissionActivity = false; });

**Comment by HarelM** [comment] 2022-06-06 04:51
Seems like a duplicate of #48.
Feel free to send a PR to update the documentation or the code with the needed information/permission :-)
I'm using raw provider, so it might explain why I don't see this crash...

**Comment by atmanegara** [comment] 2022-06-06 06:22
solved , after install android permission plugin

> Use the android permission plugin and request for the permission before asking the location permission


solved , after install android permission plugin, thank's sir

**Closed as completed** 2022-06-06 22:13 UTC
