### ISSUE TITLE
App Crash FLAG MUTABLE OR IMUTABLE

### ISSUE THREAD

**Issue by lepokoloko** [HaylLtd/cordova-plugin-background-geolocation#121] opened 2022-10-06 05:18 UTC
**Describe the bug**

APP CLOSE ON CHANGE PAGE IN APP.

LOG : ->

FATAL EXCEPTION: mainjava.lang.RuntimeException: Unable to start service com.marianhello.bgloc.service.LocationServiceImpl@2957475 with null: java.lang.IllegalArgumentException: io.uppermesh.tecnico: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
                                                                                                    	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalArgumentException: io.uppermesh.tecnico: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
                                                                                                    	at com.marianhello.bgloc.provider.ActivityRecognitionLocationProvider.onCreate(ActivityRecognitionLocationProvider.java:52)
                                                                                                    	at com.marianhello.bgloc.service.LocationServiceImpl.start(LocationServiceImpl.java:359)
                                                                                                    	at com.marianhello.bgloc.service.LocationServiceImpl.onStartCommand(LocationServiceImpl.java:274)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
                                                                                                    	... 9 common frames omitted
2022-10-06 02:11:39.149  1529-2302  ActivityManager         pid-1529                             W  crash : io.uppermesh.tecnico,10473

**Comment by HarelM** [comment] 2022-10-06 05:34
Looks like a duplicate of #119.
Please make sure you are using the right version of the plugin, that it's up to date and that you are targeting the right android sdk.

**Closed as completed by HarelM** 2022-10-06 05:34 UTC
